[package]
authors = ["Alvaro Polo <alvaro.polo@cabify.com>"]
build = "build.rs"
name = "hemu"
version = "0.1.0"

[features]
nightly = []

[dependencies]
byteorder = "1.2"
num-traits = "0.2"

[dev-dependencies]
rand = "0.5"

[build-dependencies]
rustc_version = "0.1.*"

[lib]
name = "hemu"

[[bin]]
name = "c80"
path = "src/bin/c80/main.rs"
